// vue/app-list/src/components/FriendList.vue
<script>
  export default {
    name: "FriendList",
    props: ["list"],
    methods: {
      removeItem: function(el) {
        // console.log(el);
        // console.log(this.list.indexOf(el));
        if (this.list.indexOf(el) > -1) {
          this.list.splice(this.list.indexOf(el), 1)
        }
      }
    },
    data() {
      return {
        msg: "FriendList"
      };
    }
  };
</script>

<template>
  <ul id="friendsList" class="collection">
    <li class="collection-item avatar" v-for="item in list">
      <i class="material-icons circle green">insert_chart</i>
      <span class="title" v-if="item.gender === 'male'">Mr</span>
      <span class="title" v-else>Mss</span>
      <span>{{item.name}}</span>
      <span>{{item.lastNane}}</span>
      <p class="item-email">{{item.email}}</p>
      <a href="#!" v-on:click.prevent="removeItem(item)" class="secondary-content"><i class ="material-icons">delete</i></a>
    </li>
  </ul>
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  h1,
  h2 {
    font-weight: normal;
  }
</style>

// react/app-list/src/components/list/FriendList.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

class FriendList extends Component {
  constructor(props) {
    super();
    this.state = {
      list : props.initialList
    }

  }
  gender(el) {
    var result = (el === "male") ? <span>Mr</span> : <span>Ms</span>;
    return (result);
  }

  removeItem(el) {
    console.log(el);
    console.log(this.state.list.indexOf(el));
    if (this.state.list.indexOf(el) > - 1) {
      this.state.list.splice(this.state.list.indexOf(el), 1)
      // this.setState({ list: t });
      this.setState({ list: this.state.list });
    }
  }
  
  render() {
    let arraylist = [];

    // fill up our friend list
    this.state.list.forEach((el, i) => {
      arraylist.push(
        <li className="collection-item avatar" key={i}>
          <i className="material-icons circle green">insert_chart</i>
          <span className="title">{this.gender(el.gender)} {el.name}</span>
          <span>{el.lastNane}</span>
          <p className="item-email">{el.email}</p>
          <a href="#!" onClick={() => this.removeItem(el)} className="secondary-content"><i className="material-icons">delete</i></a>
        </li >
      );
    });

    // console.log(this.props);
    return (
      <ul id="friendsList" className="collection">
        {arraylist}
        {/* or simply {this.props.list.map((el, i) =><li key={i}> name: {el.name}</li>)}*/}
      </ul>
    );
  }
}

FriendList.propTypes = {
  list: PropTypes.array
}

export default FriendList;
