// vue/app-list/src/components/FriendList.vue
<script>
  export default {
    name: "FriendList",
    props: ["list"],
    methods: {
      removeItem: function(el) {
        // console.log(el);
        // console.log(this.list.indexOf(el));
        if (this.list.indexOf(el) > -1) {
          this.list.splice(this.list.indexOf(el), 1)
        }
      }
    },
    data() {
      return {
        msg: "FriendList"
      };
    }
  };
</script>

<template>
  <ul id="friendsList" class="collection">
    <li class="collection-item avatar" v-for="item in list">
      <i class="material-icons circle green">insert_chart</i>
      <span class="title" v-if="item.gender === 'male'">Mr</span>
      <span class="title" v-else>Mss</span>
      <span>{{item.name}}</span>
      <span>{{item.lastNane}}</span>
      <p class="item-email">{{item.email}}</p>
      <a href="#!" v-on:click.prevent="removeItem(item)" class="secondary-content"><i class ="material-icons">delete</i></a>
    </li>
  </ul>
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  h1,
  h2 {
    font-weight: normal;
  }
</style>

// angular/app-list/src/app/components/friendList/friendList.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Friend } from '../friend';

@Component({
  selector: 'friend-list',
  templateUrl: './friendlist.component.html',
  styleUrls: ['./friendlist.component.css']
})
export class FriendList implements OnInit {
  @Input() list: Array<Friend>;
  title = 'FriendList app';

  removeItem = function (el) {
    console.log('remove item ' + el.name);
    console.log(this.list.indexOf(el));
    if (this.list.indexOf(el) > - 1) {
      this.list.splice(this.list.indexOf(el), 1)
    }
  }

  ngOnInit() {
    console.log("Component Friend-List ready");
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <ul id="friendsList" class="collection">
    <li class="collection-item avatar" *ngFor="let item of list">
      <i class="material-icons circle green">insert_chart</i>
      <div class="row">
        <div class="col s12">
          <span class="title" *ngIf="item.gender === 'female'; else isMr">Mss</span>
          <ng-template #isMr>
            <span class="title">Mr</span>
          </ng-template>
          <span>{{item.name}}</span>
          <span>{{item.lastName}}</span>
          <p class="item-email">{{item.email}}</p>
        </div>
        <!-- <div class="col s4"> -->
          <!-- <div class="item-age"><span>age: {{item.age}}</span></div> -->
        <!-- </div> -->
      </div>
      <a href="#!" class="secondary-content" (click)="removeItem(item)">
        <i class="material-icons">delete</i>
      </a>

    </li>
  </ul>
</div>
