// react/app-list/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';


import FriendList from './components/list/FriendList';

class App extends Component {

  render() {

    let friendList = [{
      name: "John",
      lastNane: "Doe",
      age: 27,
      email: "johndoecontact@testcontact.com",
      gender: "male"
    }, {
      name: "Mario",
      lastNane: "Rossi",
      age: 32,
      email: "mariorossi@testcontact.com",
      gender: "male"
    }, {
      name: "Lisa",
      lastNane: "Do3",
      age: 30,
      email: "lisadoe@testcontact.com",
      gender: "female"
    }];
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Friends Application - React</h1>
        </header>
        <div className="container">

          <div className="row">

            <div className="col s12 m4 l4">parte utente
            </div>
            <div className="col s12 m8 l8">
              <FriendList initialList={friendList}></FriendList>
            </div>

          </div>

        </div>

      </div>
    );
  }
}

export default App;

// angular/app-list/src/app/app.component.ts
import { Component } from '@angular/core';
import { Friend } from './components/friend';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'app';
  friendList: Friend[] = [{
    name: "John",
    lastName: "Doe",
    age: 27,
    email: "johndoecontact@testcontact.com",
    gender: "male"
  }, {
    name: "Mario",
    lastName: "Rossi",
    age: 32,
    email: "mariorossi@testcontact.com",
    gender: "male"
  }, {
    name: "Lisa",
    lastName: "Do3",
    age: 30,
    email: "lisadoe@testcontact.com",
    gender: "female"
  }];
}

<div>
  <header class="App-header">
    <img width="300" class="App-logo" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
    <h1 class="App-title">Friends Application - Angular</h1>
  </header>
  <div class="container">
    <div class="row">
      <div class="col s12 m4 l4">parte utente
      </div>
      <div class="col s12 m8 l8">
        <friend-list [list]="friendList"></friend-list>
      </div>
    </div>
    <add-friend [list]="friendList"></add-friend>
  </div>
</div>
